Remove the no longer used `LogConfiguration`. RoutingProfile now defaults to .driving
ably/ably-asset-tracking-swift pull request #331
Opened 2022-08-18 09:10 UTC by JakubJankowski

2022-08-18 13:30 UTC, KacperKluka requested changes
Everything is okay, but please update the README as a part of this PR :wink:

2022-08-19 08:39 UTC, JakubJankowski commented
I've updated the readme as part of this [PR](https://github.com/ably/ably-asset-tracking-swift/pull/332), to avoid merge conflicts, and since they would be landed at pretty much the same time 😉 But no problem, I can update the readme here as well.

2022-08-19 08:41 UTC, KacperKluka approved these changes
LGTM :+1:

2022-08-19 08:52 UTC, arturjaworski approved these changes

2022-08-19 09:26 UTC, merged