Fail subscriber if malformed message received
ably/ably-asset-tracking-swift pull request #360
Opened 2022-08-30 10:27 UTC by lawrence-forooghian

This makes `DefaultSubscriber` fail with an [invalid message error](https://github.com/ably/ably-asset-tracking-common/tree/main/specification#error-codes) if it receives a malformed location update. The behaviour is roughly as in https://github.com/ably/ably-asset-tracking-android/issues/691. See commit messages for more details.

2022-08-30 15:20 UTC, ikbalkaya requested changes
Only a minor vertical space change otherwise looks good

2022-08-31 08:27 UTC, KacperKluka approved these changes
I did a brief review and from the functional point of view this PR looks good :+1:

2022-08-31 10:42 UTC, ikbalkaya commented on Tests/SubscriberTests/Mocks/GeneratedMocks.swift
> +
I realize this is from a generated file so I'll resolve and approve

2022-08-31 10:42 UTC, ikbalkaya approved these changes

2022-09-01 15:16 UTC, QuintinWillison commented
Removing my review request. If @ikbalkaya and @KacperKluka are happy then please merge.

2022-09-02 15:08 UTC, merged