Expose publisher presence information to subscriber
ably/ably-asset-tracking-swift pull request #383
Opened 2022-09-29 20:33 UTC by lawrence-forooghian

## What this does

This adds a new delegate method `SubscriberDelegate.subscriber(sender: Subscriber, didUpdatePublisherPresence isPresent: Bool)`, which informs the subscriber whether the publisher is present. I believe it's intended to provide more granular information than the existing `SubscriberDelegate.subscriber(sender: Subscriber, didChangeAssetConnectionStatus status: ConnectionState)` method (see https://github.com/ably/ably-asset-tracking-common/issues/58).

It also adds a new label in the subscriber example app to display this information.

Behaviour copied from https://github.com/ably/ably-asset-tracking-android/pull/754.

## Video of new label in subscriber example app

https://user-images.githubusercontent.com/53756884/193136258-3cbfded7-15ee-48e9-8696-08960b1a50f5.mov

2022-09-30 14:18 UTC, ikbalkaya requested changes
Code looks good to me. Can you update Readme for an example usage of this?

2022-10-03 13:30 UTC, lawrence-forooghian commented
@ikbalkaya do you think it's necessary to add it to the Readme? It's a pretty niche feature, and our Readme currently just gives a very top-level of how to use the SDK. I know that [Quintin asked for it to be added to the Android Readme](https://github.com/ably/ably-asset-tracking-android/pull/754#pullrequestreview-1102069608), but it seems that was more to do with explaining what compiler settings need to be enabled to opt in to the experimental features. We don't have an equivalent here.

2022-10-03 13:52 UTC, KacperKluka approved these changes
LGTM 👍  However, I've only changed the SDK related code, as I'm not an iOS dev 😉

2022-10-03 15:30 UTC, ikbalkaya approved these changes

2022-10-04 12:36 UTC, merged